version: "3"
services:
  db-postgres:
    container_name: db-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD:  '${POSTGRES_PASSWORD:-admindev007}'
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    #ports:
    # - 8080:8080
    environment:
      PGADMIN_DEFAULT_EMAIL:  '${PGADMIN_DEFAULT_EMAIL:-admindev@isha.org}'
      PGADMIN_DEFAULT_PASSWORD: '${PGADMIN_DEFAULT_PASSWORD:-admindev007}'
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:            

